global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'uptime-kuma'
    static_configs:
      - targets: ['uptime-kuma:3001']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100'] 